/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package template

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.utils.env
import dev.kord.common.entity.Snowflake
import template.extensions.ApplicationsExtension
import java.nio.file.Path
import kotlin.io.path.createDirectory
import kotlin.io.path.div
import kotlin.io.path.exists

internal val dataDirectory = Path.of("./data/")
internal val dataFile = dataDirectory / "config.properties"

private val TOKEN = env("TOKEN")   // Get the bot' token from the env vars or a .env file
internal val GUILD_ID = Snowflake(env("GUILD_ID"))

suspend fun main() {
    if (!dataDirectory.exists()) {
        dataDirectory.createDirectory()
    }

    val bot = ExtensibleBot(TOKEN) {
        extensions {
            add(::ApplicationsExtension)
        }
    }

    bot.start()
}
